// The Illustration Snap template library: ~15 starter symbols, each with
// (a) synthetic point-cloud examples for $Q matching and (b) a replacement
// recipe of clean canvas primitives.
//
// The examples here are v1 synthetic templates, generated by deterministic
// functions (same approach as shapeSnap/testInk.ts). The template capture
// tooling (capture.ts: __templateCapture) is the path for replacing them
// with real drawn examples: draw the symbol on the device, save the JSON,
// and paste the stroke arrays in as additional examples.
//
// Replacement recipes are expressed in each template's own design space and
// scaled (non-uniformly) so the recipe's bounds land exactly on the drawn
// bounds. Symbols with a matching tldraw geo style use a single geo shape
// (star, cloud, heart, triangle); the rest compose geo/line/draw primitives
// that the wiring groups into one shape.

import type { InkPoint } from '../shapeSnap/recognize'
import { seededRandom } from '../shapeSnap/testInk'
import { QDollarRecognizer } from './qdollar'

// Maximum $Q greedy cloud distance for a match; beyond this the strokes stay
// Ink. Tuned against the synthetic fixtures: jittered rough drawings of the
// templates measure ~0.07–1.72 while geometric-shape and handwriting
// negatives measure above ~2.4 (see qdollar.test.ts, which asserts both
// sides). Templates that sit close to a plain geometric shape additionally
// carry a tighter per-template maxDistance.
export const ILLUSTRATION_MAX_DISTANCE = 2.0

export interface StrokeOpts {
  jitter?: number
  seed?: number
}

export type IllustrationName =
  | 'stick-figure'
  | 'star'
  | 'cloud'
  | 'checkmark'
  | 'x'
  | 'question-mark'
  | 'exclamation-mark'
  | 'heart'
  | 'lightbulb'
  | 'speech-bubble'
  | 'cylinder'
  | 'document'
  | 'gear'
  | 'smiley'
  | 'triangle'

// Replacement parts, in template design-space coordinates. 'geo' fill
// defaults to the drawn Ink's fill; 'solid' marks accents (dots, eyes).
export type ReplacementPart =
  | {
      kind: 'geo'
      geo: 'ellipse' | 'rectangle' | 'triangle' | 'star' | 'cloud' | 'heart' | 'oval'
      x: number
      y: number
      w: number
      h: number
      fill?: 'solid'
    }
  | { kind: 'line'; points: InkPoint[] }
  | { kind: 'draw'; points: InkPoint[]; closed?: boolean }

export interface IllustrationTemplate {
  name: IllustrationName
  examples: InkPoint[][][] // examples -> strokes -> points
  replacement: ReplacementPart[]
  // Minimum candidate stroke count for this template to compete (default 1).
  // $Q itself is articulation-invariant, but some symbols genuinely require
  // separate strokes — an exclamation mark without a lifted-pen dot is just a
  // line — and gating on it keeps plain single strokes from matching them.
  minStrokes?: number
  // Per-template rejection bar overriding ILLUSTRATION_MAX_DISTANCE, for
  // templates that sit close to a plain geometric shape in $Q space.
  maxDistance?: number
}

// --- stroke generators (deterministic; jitter/seed like testInk.ts) --------

type Rand = () => number

function jit(rand: Rand, jitter: number): number {
  return (rand() - 0.5) * 2 * jitter
}

// Straight polyline through waypoints, ~perSeg points per segment.
function polyline(
  waypoints: readonly InkPoint[],
  { jitter = 0, seed = 1, perSeg = 10 }: StrokeOpts & { perSeg?: number } = {}
): InkPoint[] {
  const rand = seededRandom(seed)
  const points: InkPoint[] = []
  for (let s = 0; s < waypoints.length - 1; s++) {
    const a = waypoints[s]
    const b = waypoints[s + 1]
    for (let i = 0; i < perSeg; i++) {
      const t = i / perSeg
      points.push({
        x: a.x + (b.x - a.x) * t + jit(rand, jitter),
        y: a.y + (b.y - a.y) * t + jit(rand, jitter),
      })
    }
  }
  points.push({ ...waypoints[waypoints.length - 1] })
  return points
}

// Elliptical arc in screen coordinates (y grows downward): angle 0 is +x,
// π/2 is downward.
function arc(
  cx: number,
  cy: number,
  rx: number,
  ry: number,
  fromAngle: number,
  toAngle: number,
  { jitter = 0, seed = 1, n = 24 }: StrokeOpts & { n?: number } = {}
): InkPoint[] {
  const rand = seededRandom(seed)
  const points: InkPoint[] = []
  for (let i = 0; i < n; i++) {
    const a = fromAngle + ((toAngle - fromAngle) * i) / (n - 1)
    points.push({
      x: cx + rx * Math.cos(a) + jit(rand, jitter),
      y: cy + ry * Math.sin(a) + jit(rand, jitter),
    })
  }
  return points
}

function dot(cx: number, cy: number, r: number, opts: StrokeOpts = {}): InkPoint[] {
  return arc(cx, cy, r, r, 0, Math.PI * 2, { ...opts, n: 10 })
}

// Each generator returns the symbol's strokes in its design space (~200x200).
// Tests reuse them with different jitter/seed to make rough drawings that are
// genuinely distinct from the registered templates.

export function stickFigureStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const seed = opts.seed ?? 1
  return [
    arc(100, 32, 22, 22, -Math.PI / 2, (Math.PI * 3) / 2, { ...opts, seed, n: 26 }),
    polyline([{ x: 100, y: 56 }, { x: 100, y: 128 }], { ...opts, seed: seed + 1 }),
    polyline([{ x: 58, y: 88 }, { x: 142, y: 88 }], { ...opts, seed: seed + 2 }),
    polyline([{ x: 100, y: 128 }, { x: 64, y: 186 }], { ...opts, seed: seed + 3 }),
    polyline([{ x: 100, y: 128 }, { x: 136, y: 186 }], { ...opts, seed: seed + 4 }),
  ]
}

export function starStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const cx = 100
  const cy = 105
  const R = 90
  const r = 38
  const vertices: InkPoint[] = []
  for (let k = 0; k < 5; k++) {
    const outer = -Math.PI / 2 + (k * 2 * Math.PI) / 5
    const inner = outer + Math.PI / 5
    vertices.push({ x: cx + R * Math.cos(outer), y: cy + R * Math.sin(outer) })
    vertices.push({ x: cx + r * Math.cos(inner), y: cy + r * Math.sin(inner) })
  }
  vertices.push(vertices[0])
  return [polyline(vertices, { ...opts, perSeg: 5 })]
}

export function cloudStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const seed = opts.seed ?? 1
  const jitter = opts.jitter ?? 0
  const rand = seededRandom(seed)
  const points: InkPoint[] = []
  const n = 56
  for (let i = 0; i < n; i++) {
    const a = (2 * Math.PI * i) / (n - 1)
    const bump = 1 + 0.22 * Math.abs(Math.sin(2.5 * a + 0.4))
    points.push({
      x: 100 + 90 * bump * Math.cos(a) + jit(rand, jitter),
      y: 100 + 55 * bump * Math.sin(a) + jit(rand, jitter),
    })
  }
  return [points]
}

export function checkmarkStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  return [polyline([{ x: 20, y: 110 }, { x: 78, y: 168 }, { x: 180, y: 32 }], { ...opts, perSeg: 14 })]
}

export function xStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const seed = opts.seed ?? 1
  return [
    polyline([{ x: 30, y: 30 }, { x: 170, y: 170 }], { ...opts, seed, perSeg: 14 }),
    polyline([{ x: 170, y: 30 }, { x: 30, y: 170 }], { ...opts, seed: seed + 1, perSeg: 14 }),
  ]
}

function questionMarkHook(opts: StrokeOpts = {}): InkPoint[] {
  const seed = opts.seed ?? 1
  return [
    ...arc(100, 62, 40, 40, Math.PI, 2 * Math.PI, { ...opts, seed, n: 20 }),
    ...polyline(
      [
        { x: 140, y: 62 },
        { x: 132, y: 88 },
        { x: 106, y: 102 },
        { x: 100, y: 118 },
        { x: 100, y: 134 },
      ],
      { ...opts, seed: seed + 1, perSeg: 4 }
    ),
  ]
}

export function questionMarkStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const seed = opts.seed ?? 1
  return [questionMarkHook(opts), dot(100, 172, 5, { ...opts, seed: seed + 2 })]
}

export function exclamationMarkStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const seed = opts.seed ?? 1
  return [
    polyline([{ x: 100, y: 24 }, { x: 100, y: 128 }], { ...opts, seed, perSeg: 14 }),
    dot(100, 170, 5, { ...opts, seed: seed + 1 }),
  ]
}

export function heartStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const seed = opts.seed ?? 1
  const jitter = opts.jitter ?? 0
  const rand = seededRandom(seed)
  const points: InkPoint[] = []
  const n = 56
  const s = 5.2
  for (let i = 0; i < n; i++) {
    const t = (2 * Math.PI * i) / (n - 1)
    points.push({
      x: 100 + s * 16 * Math.sin(t) ** 3 + jit(rand, jitter),
      y:
        90 -
        s * (13 * Math.cos(t) - 5 * Math.cos(2 * t) - 2 * Math.cos(3 * t) - Math.cos(4 * t)) +
        jit(rand, jitter),
    })
  }
  return [points]
}

export function lightbulbStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const seed = opts.seed ?? 1
  return [
    arc(100, 78, 46, 46, -Math.PI / 2, (Math.PI * 3) / 2, { ...opts, seed, n: 30 }),
    polyline(
      [
        { x: 84, y: 128 },
        { x: 116, y: 128 },
        { x: 116, y: 152 },
        { x: 84, y: 152 },
        { x: 84, y: 128 },
      ],
      { ...opts, seed: seed + 1, perSeg: 5 }
    ),
  ]
}

export function speechBubbleStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  return [
    polyline(
      [
        { x: 35, y: 25 },
        { x: 165, y: 25 },
        { x: 165, y: 105 },
        { x: 85, y: 105 },
        { x: 62, y: 140 },
        { x: 66, y: 105 },
        { x: 35, y: 105 },
        { x: 35, y: 25 },
      ],
      { ...opts, perSeg: 7 }
    ),
  ]
}

function cylinderBody(opts: StrokeOpts = {}): InkPoint[] {
  const seed = opts.seed ?? 1
  return [
    ...polyline([{ x: 38, y: 42 }, { x: 38, y: 138 }], { ...opts, seed, perSeg: 10 }),
    ...arc(100, 138, 62, 20, Math.PI, 0, { ...opts, seed: seed + 1, n: 18 }),
    ...polyline([{ x: 162, y: 138 }, { x: 162, y: 42 }], { ...opts, seed: seed + 2, perSeg: 10 }),
  ]
}

export function cylinderStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const seed = opts.seed ?? 1
  return [
    arc(100, 42, 62, 20, 0, 2 * Math.PI, { ...opts, seed: seed + 3, n: 28 }),
    cylinderBody(opts),
  ]
}

// Portrait page with a pronounced wavy bottom edge — both deliberate, so a
// plain rectangle (landscape or portrait) stays clearly distinct in $Q space.
function documentOutline(opts: StrokeOpts = {}): InkPoint[] {
  const seed = opts.seed ?? 1
  const jitter = opts.jitter ?? 0
  const rand = seededRandom(seed + 9)
  const wave: InkPoint[] = []
  const n = 20
  for (let i = 0; i < n; i++) {
    const t = i / (n - 1)
    wave.push({
      x: 155 - 110 * t + jit(rand, jitter),
      y: 160 + 30 * Math.sin(2 * Math.PI * t) + jit(rand, jitter),
    })
  }
  return [
    ...polyline(
      [{ x: 45, y: 20 }, { x: 155, y: 20 }, { x: 155, y: 160 }],
      { ...opts, seed, perSeg: 12 }
    ),
    ...wave,
    ...polyline([{ x: 45, y: 160 }, { x: 45, y: 20 }], { ...opts, seed: seed + 1, perSeg: 12 }),
  ]
}

export function documentStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  return [documentOutline(opts)]
}

function gearOutline(opts: StrokeOpts = {}): InkPoint[] {
  const seed = opts.seed ?? 1
  const jitter = opts.jitter ?? 0
  const rand = seededRandom(seed)
  const R = 88
  const r = 64
  const teeth = 8
  const points: InkPoint[] = []
  const deg = Math.PI / 180
  for (let k = 0; k < teeth; k++) {
    const a0 = (k * 2 * Math.PI) / teeth
    const sector = [
      { radius: R, a: a0 },
      { radius: R, a: a0 + 20 * deg },
      { radius: r, a: a0 + 25 * deg },
      { radius: r, a: a0 + 40 * deg },
    ]
    for (const { radius, a } of sector) {
      points.push({
        x: 100 + radius * Math.cos(a) + jit(rand, jitter),
        y: 100 + radius * Math.sin(a) + jit(rand, jitter),
      })
    }
  }
  points.push({ ...points[0] })
  return points
}

export function gearStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  return [gearOutline(opts)]
}

function smileyMouth(opts: StrokeOpts = {}): InkPoint[] {
  return arc(100, 90, 58, 58, 0.15 * Math.PI, 0.85 * Math.PI, { ...opts, n: 16 })
}

export function smileyStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  const seed = opts.seed ?? 1
  return [
    arc(100, 100, 85, 85, -Math.PI / 2, (Math.PI * 3) / 2, { ...opts, seed, n: 40 }),
    dot(68, 72, 6, { ...opts, seed: seed + 1 }),
    dot(132, 72, 6, { ...opts, seed: seed + 2 }),
    smileyMouth({ ...opts, seed: seed + 3 }),
  ]
}

export function triangleStrokes(opts: StrokeOpts = {}): InkPoint[][] {
  return [
    polyline(
      [{ x: 100, y: 25 }, { x: 180, y: 168 }, { x: 20, y: 168 }, { x: 100, y: 25 }],
      { ...opts, perSeg: 12 }
    ),
  ]
}

// --- the library ------------------------------------------------------------

export const ILLUSTRATION_TEMPLATES: readonly IllustrationTemplate[] = [
  {
    name: 'stick-figure',
    minStrokes: 3,
    examples: [stickFigureStrokes()],
    replacement: [
      { kind: 'geo', geo: 'ellipse', x: 78, y: 10, w: 44, h: 44 },
      { kind: 'line', points: [{ x: 100, y: 54 }, { x: 100, y: 128 }] },
      { kind: 'line', points: [{ x: 58, y: 88 }, { x: 142, y: 88 }] },
      { kind: 'line', points: [{ x: 100, y: 128 }, { x: 64, y: 186 }] },
      { kind: 'line', points: [{ x: 100, y: 128 }, { x: 136, y: 186 }] },
    ],
  },
  {
    name: 'star',
    examples: [starStrokes()],
    replacement: [{ kind: 'geo', geo: 'star', x: 0, y: 0, w: 100, h: 100 }],
  },
  {
    name: 'cloud',
    examples: [cloudStrokes()],
    replacement: [{ kind: 'geo', geo: 'cloud', x: 0, y: 0, w: 100, h: 100 }],
  },
  {
    name: 'checkmark',
    examples: [checkmarkStrokes()],
    replacement: [
      { kind: 'line', points: [{ x: 20, y: 110 }, { x: 78, y: 168 }, { x: 180, y: 32 }] },
    ],
  },
  {
    name: 'x',
    minStrokes: 2,
    examples: [xStrokes()],
    replacement: [
      { kind: 'line', points: [{ x: 30, y: 30 }, { x: 170, y: 170 }] },
      { kind: 'line', points: [{ x: 170, y: 30 }, { x: 30, y: 170 }] },
    ],
  },
  {
    name: 'question-mark',
    minStrokes: 2,
    examples: [questionMarkStrokes()],
    replacement: [
      { kind: 'draw', points: questionMarkHook() },
      { kind: 'geo', geo: 'ellipse', x: 94, y: 166, w: 12, h: 12, fill: 'solid' },
    ],
  },
  {
    name: 'exclamation-mark',
    minStrokes: 2,
    examples: [exclamationMarkStrokes()],
    replacement: [
      { kind: 'line', points: [{ x: 100, y: 24 }, { x: 100, y: 128 }] },
      { kind: 'geo', geo: 'ellipse', x: 94, y: 164, w: 12, h: 12, fill: 'solid' },
    ],
  },
  {
    name: 'heart',
    examples: [heartStrokes()],
    replacement: [{ kind: 'geo', geo: 'heart', x: 0, y: 0, w: 100, h: 100 }],
  },
  {
    name: 'lightbulb',
    minStrokes: 2,
    examples: [lightbulbStrokes()],
    replacement: [
      { kind: 'geo', geo: 'ellipse', x: 54, y: 32, w: 92, h: 92 },
      { kind: 'geo', geo: 'rectangle', x: 84, y: 128, w: 32, h: 24 },
    ],
  },
  {
    name: 'speech-bubble',
    examples: [speechBubbleStrokes()],
    replacement: [
      { kind: 'geo', geo: 'oval', x: 30, y: 20, w: 140, h: 90 },
      {
        kind: 'draw',
        points: [{ x: 84, y: 103 }, { x: 62, y: 140 }, { x: 65, y: 103 }],
        closed: true,
      },
    ],
  },
  {
    name: 'cylinder',
    minStrokes: 2,
    examples: [cylinderStrokes()],
    replacement: [
      { kind: 'geo', geo: 'ellipse', x: 38, y: 22, w: 124, h: 40 },
      { kind: 'draw', points: cylinderBody() },
    ],
  },
  {
    name: 'document',
    // The document silhouette is a portrait rectangle but for its wavy
    // bottom, so it competes under a tighter bar: rough documents measure
    // ~0.5 while portrait rectangles measure ~1.5+ (see qdollar.test.ts).
    maxDistance: 1.0,
    examples: [documentStrokes()],
    replacement: [{ kind: 'draw', points: documentOutline(), closed: true }],
  },
  {
    name: 'gear',
    examples: [gearStrokes()],
    replacement: [
      { kind: 'draw', points: gearOutline(), closed: true },
      { kind: 'geo', geo: 'ellipse', x: 74, y: 74, w: 52, h: 52 },
    ],
  },
  {
    name: 'smiley',
    minStrokes: 3,
    examples: [smileyStrokes()],
    replacement: [
      { kind: 'geo', geo: 'ellipse', x: 15, y: 15, w: 170, h: 170 },
      { kind: 'geo', geo: 'ellipse', x: 62, y: 66, w: 12, h: 12, fill: 'solid' },
      { kind: 'geo', geo: 'ellipse', x: 126, y: 66, w: 12, h: 12, fill: 'solid' },
      { kind: 'draw', points: smileyMouth() },
    ],
  },
  {
    name: 'triangle',
    examples: [triangleStrokes()],
    replacement: [{ kind: 'geo', geo: 'triangle', x: 0, y: 0, w: 100, h: 100 }],
  },
]

// --- matching ---------------------------------------------------------------

export interface IllustrationMatch {
  name: IllustrationName
  distance: number
  template: IllustrationTemplate
}

let recognizer: QDollarRecognizer | undefined

function getRecognizer(): QDollarRecognizer {
  if (!recognizer) {
    recognizer = new QDollarRecognizer()
    for (const template of ILLUSTRATION_TEMPLATES) {
      for (const example of template.examples) {
        recognizer.addTemplate(template.name, example)
      }
    }
  }
  return recognizer
}

export function getIllustrationTemplate(name: string): IllustrationTemplate | undefined {
  return ILLUSTRATION_TEMPLATES.find((t) => t.name === name)
}

// Match a group of Ink strokes against the library; null when nothing clears
// the rejection bar. Templates whose minStrokes exceeds the candidate's
// stroke count don't compete.
export function recognizeIllustration(
  strokes: readonly (readonly InkPoint[])[]
): IllustrationMatch | null {
  const strokeCount = strokes.filter((s) => s.length > 0).length
  const match = getRecognizer().recognize(strokes, (name) => {
    const template = getIllustrationTemplate(name)
    return (template?.minStrokes ?? 1) <= strokeCount
  })
  if (match.name === null) return null
  const template = getIllustrationTemplate(match.name)
  if (!template) return null
  // If the overall winner fails its (possibly tighter) bar, the whole group
  // stays Ink — no fallback to the runner-up, which by definition fit worse.
  const bar = Math.min(ILLUSTRATION_MAX_DISTANCE, template.maxDistance ?? Infinity)
  if (match.distance > bar) return null
  return { name: template.name, distance: match.distance, template }
}
